#ifndef _GLOBALS_H_
#define _GLOBALS_H_

#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>


#ifndef FALSE
#define FALSE 0
#endif

#ifndef TRUE
#define TRUE 1
#endif

#define MAXTOKENLEXEME 112

typedef enum {
		ENDFILETKN,ERROR,IFTKN,ENDIFTKN,ELSETKN,FUNCTKN,ENDFUNCTKN,RETURNFUNCTKN,
		WHILETKN,ENDWHILETKN,READTKN,WRITETKN,IDTKN,MATRUSHKATKN,ENDMATRUSHKATKN,
		MESSAGETKN,INTTKN,DOUBLETKN,STRINGTKN,BOOLTKN,TRUETKN,FALSETKN,STRINGVALTKN,
		INTVALTKN,DOUBLEVALTKN,ASSIGNTKN,PLUSTKN,MINUSTKN,TIMESTKN,DIVTKN,LTTKN,LTETKN,
		GTTKN,GTETKN,EQUALTKN,NOTEQUALTKN,ASSIGNSECRETTKN,ORTKN,ANDTKN,LEFTPTKN,RIGHTPTKN,
		SEMICOLONTKN,LEFTBTKN,RIGHTBTKN,COMMATKN,OPENBLOCKTKN
} Token;

extern FILE* inputFile;
extern FILE* outputFile;
extern int lineno;
extern char lexeme[MAXTOKENLEXEME+1];

Token nextToken(void);
#endif